name: Demo
on: [push]
jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: ./setup_server.sh
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./build_server.sh
        
        
  display:
    runs-on: ubuntu-latest
    steps:
      - name: print a value
        run: echo Hello from another job


         
      
