name: Demo
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
   
        
  display:
    runs-on: ubuntu-latest
    steps:
      - name: print a value
        run: echo Hello from another job
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello


         
      
